services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # - NGROK_TUNNEL_AUTO_DETECT=http://ngrok:4040
      # - INSTALL_MODULES_DIR=/ps-modules
      - PS_DOMAIN=localhost:8000
      - DEBUG_MODE=false
    ports:
      - ${HOST_PORT_BIND_PRESTASHOP:?See .env.dist}:80

  mysql:
    image: mariadb:${DOCKER_VERSION_MARIADB:?See .env.dist}
    env_file:
      - .env
    environment:
      - TZ=UTC
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=prestashop",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${HOST_PORT_BIND_MARIADB:?See .env.dist}:3306

  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - ${HOST_PORT_BIND_PHP_MY_ADMIN:?See .env.dist}:80
