services:
  prestashop:
    image: flashlight:8.2.1-debian-apache
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ADMIN_MAIL_OVERRIDE=titi@toto.com
      - ADMIN_PASSWORD_OVERRIDE=pedoncule
      - PS_DOMAIN=localhost
      - SSL_REDIRECT=true
    volumes:
      - ./assets/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop