name: flashlight-xdebug-prestashop
services:
  prestashop:
    image: prestashop/prestashop-flashlight:nightly
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=localhost:8000
      - INIT_SCRIPTS_DIR=/tmp/init-scripts
      - INIT_SCRIPTS_USER=root
      - XDEBUG_ENABLED=true
    volumes:
      - ./PrestaShop:/var/www/html:rw
    ports:
      - 8000:80

  mysql:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
