services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    depends_on:
      mysql:
        condition: service_healthy
      ngrok:
        condition: service_started
    environment:
      - NGROK_TUNNEL_AUTO_DETECT=http://ngrok:4040
    ports:
      - 8000:80

  mysql:
    image: mariadb:lts
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=prestashop",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop

  ngrok:
    image: ngrok/ngrok
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4040 || exit 1"]
      interval: 10s
      timeout: 2s
      start_period: 10s
    volumes:
      - ./ngrok.yml:/var/lib/ngrok/ngrok.yml
    expose:
      - 4040
