name: flashlight-cloudflared-tunnel
services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    depends_on:
      mysql:
        condition: service_healthy
      cloudflared:
        condition: service_started
    environment:
      - PS_DOMAIN=${TUNNEL_NAME}
      - PS_PROTOCOL=https
    ports:
      - 8000:80

  mysql:
    image: mariadb:lts
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=prestashop",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run $${TUNNEL_NAME}
    environment:
      - TUNNEL_CRED_FILE=/credentials.json
      - TUNNEL_URL=http://prestashop:80
      - TUNNEL_HTTP_HOST_HEADER=${TUNNEL_NAME}
    volumes:
      - ./credentials.json:/credentials.json
