name: flashlight-develop-a-module
services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=localhost:8000
      - INIT_SCRIPTS_DIR=/tmp/init-scripts
    ports:
      - 8000:80
    volumes:
      - ./init-scripts:/tmp/init-scripts:ro
      - type: bind
        source: ./modules/testmodule # local path to the module
        target: /var/www/html/modules/testmodule # path to be mounted in the container

  mysql:
    image: mariadb:lts
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=prestashop",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
