name: Docker image publish

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      flavour:
        description: "OS flavour"
        required: false
        default: "alpine"
        type: choice
        options:
          - alpine
          - debian

      server:
        description: "Server flavour"
        required: false
        default: "nginx"
        type: choice
        options:
          - nginx
          - apache

      ps_version:
        description: "The target PrestaShop version (defaults to 'latest')"
        required: false
        default: latest
        type: string

      php_version:
        description: "The target PHP version (recommended version applies by default, cf. build.sh)"
        required: false
        type: string

      tag:
        description: "Docker tag (defaults to '$ps_version-$php_version' or 'latest')"
        required: false
        type: string

      target_platforms:
        description: "Target platforms to build this image for"
        required: false
        default: "linux/amd64,linux/arm64"
        type: string

jobs:
  build_and_publish:
    name: Build and publish docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.TARGET_PLATFORMS }}
          use: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: ./build.sh
        env:
          PLATFORM: ${{ inputs.target_platforms }}
          PS_VERSION: ${{ inputs.ps_version }}
          PHP_VERSION: ${{ inputs.php_version }}
          TAG: ${{ inputs.tag }}
          PUSH: "true"
