---
name: Docker base image publish

on:
  workflow_dispatch:
    inputs:
      os_flavour:
        description: "OS flavour"
        required: false
        default: "alpine"
        type: choice
        options:
          - alpine
          - debian

      server_flavour:
        description: "Server flavour"
        required: false
        default: "nginx"
        type: choice
        options:
          - nginx
          - apache

      php_version:
        description: "The target PHP version"
        required: false
        type: string

      target_platforms:
        description: "Target platforms to build this image for"
        required: false
        default: "linux/amd64,linux/arm64"
        type: string

      runner:
        description: "The runner to use"
        required: false
        default: "self-hosted"
        type: choice
        options:
          - self-hosted
          - ubuntu-latest

jobs:
  build_and_publish:
    name: Build and publish docker
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base ${{ inputs.os_flavour }} for ${{ inputs.php_version }}
        run: ./build.sh
        env:
          TARGET_PLATFORM: ${{ inputs.target_platforms }}
          PHP_VERSION: ${{ inputs.php_version }}
          OS_FLAVOUR: ${{ inputs.os_flavour }}
          BASE_ONLY: "true"
          PUSH: "true"
          SERVER_FLAVOUR: ${{ inputs.server_flavour }}
