---
name: Docker base image publish

on:
  workflow_dispatch:
    inputs:
      os_flavour:
        description: "OS flavour"
        required: false
        default: "alpine"
        type: choice
        options:
          - alpine
          - debian

      php_version:
        description: "The target PHP version"
        required: false
        type: string

jobs:
  build_and_publish:
    name: Build and publish docker
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base ${{ inputs.os_flavour }}
        run: ./build.sh
        env:
          OS_FLAVOUR: ${{ inputs.os_flavour }}
          BASE_ONLY: "true"
          PUSH: "true"
